apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
      - name: myapp
        image: ghcr.io/frzifus/jaeger-otel-test
        args: ["-address.host=localhost", "-address.port=6831"]
        env:
          - name: OTEL_SERVICE_NAME
            value: "frzifus-otel-test"

